use_frameworks!

platform :ios, '8.0'

target 'TDAPI_Example' do
  pod 'TDAPI', :path => '../'

  target 'TDAPI_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
